#!/bin/bash
#+======================================================================
# $HeadURL: https://svnpub.codac.iter.org/codac/iter/codac/dev/units/m-rtf-model/branches/codac-core-6.2/templates/rtf/plugin/test/test.sh $
# $Id: test.sh 106494 2020-02-04 17:44:49Z lavricp $
#
# Project       : CODAC Core System
#
# Description   : Test script
#
# Author        : This script was generated by CODAC development toolkit
#
# Copyright (c) : 2010-2019 ITER Organization,
#                 CS 90 046
#                 13067 St. Paul-lez-Durance Cedex
#                 France
#
# This file is part of ITER CODAC software.
# For the terms and conditions of redistribution or use of this software
# refer to the file ITER-LICENSE.TXT located in the top level directory
# of the distribution package.
#
#-======================================================================

######################################################################
# Test scripts
######################################################################

# Add your test scripts in TEST_SCRIPTS list. They
# will be executed in order.
# 
# The test script must return non-zero value if it
# meets any error. Please use test_template.[sh|pl]
# to write a new test script.
#
# Each test script must have executable permission.
# Don't forget to add "./" before the script file name.
TEST_SCRIPTS=("make test")

# Add your test scripts that should be executed
# after the whole test script procedure. The scripts
# listed in ENSURE_SCRIPTS will be executed even if
# test procedure forcibly quits by user interruption.
# 
# The test script must return non-zero value if it
# meets any error. Please use test_template.[sh|pl]
# to write a new test script.
ENSURE_SCRIPTS=()

######################################################################
# Test execution
######################################################################

source sunit
run_tests

exit $?
